# Generated by Django 5.2.7 on 2025-11-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time_slot',
            field=models.TimeField(default='07:00'),
            preserve_default=False,
        ),
    ]
